### ISSUE TITLE
Migrar para NextJS [sugestão]

### ISSUE THREAD

**Issue by alangabrielbs** [joaotuliojt/portfolio-react#4]
Fala João, tudo bom? 

Cara, seu portfólio ficou muito foda! Achei incrível o background com a logo das techs haha

Trago aqui uma sugestão/desafio para você aprender uma coisa nova, o famosinho [**NextJS**](https://nextjs.org/)

Topa? se precisar de ajuda pra entender como funciona o NextJS, super topo de ajudar nisso.

Acho que vai ser um desafio legal...

**Comment by jhonatasmatos** [comment]
Eae João como vai? Depois de alguns meses aqui estou eu para apoiar o comentário do Alan, ao migrar seu portfólio para [NextJS](https://nextjs.org/) você melhora o SEO e ainda seu portfólio consegue funcionar com o javascript, que tal esse desafio em ? 🚀

**Comment by joaotuliojt** [comment]
Desafio aceito @jhonatasmatos, obrigado pela sugestão, irei aproveitar e já fazer algumas melhorias !🚀🚀🚀🚀

**Comment by joaotuliojt** [comment]
> Fala João, tudo bom?
> 
> Cara, seu portfólio ficou muito foda! Achei incrível o background com a logo das techs haha
> 
> Trago aqui uma sugestão/desafio para você aprender uma coisa nova, o famosinho [**NextJS**](https://nextjs.org/)
> 
> Topa? se precisar de ajuda pra entender como funciona o NextJS, super topo de ajudar nisso.
> 
> Acho que vai ser um desafio legal...

Oi Alan, agora que estou trabalhando com o Next acho que vai ser moleza HAHA! Muito obrigado pela sugestão e desculpe a demora para responder.
